# Generated by Django 3.1.7 on 2021-03-05 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('text', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
                ('category', models.CharField(max_length=150, verbose_name='Категория')),
                ('remainder', models.IntegerField(validators=[django.core.validators.MaxValueValidator(0)], verbose_name='Остаток')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MaxValueValidator(0)], verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'articles',
            },
        ),
    ]
